// ─────────────────────────────────────────────────────────────
//  services/reportEngine.js — Reusable Report Engine (Sprint 8)
//
//  Branded PDF generation using pdfkit. Provides helpers for
//  cover pages, tables, section headers, footers, and S3 upload.
// ─────────────────────────────────────────────────────────────

const PDFDocument = require('pdfkit')
const crypto = require('crypto')
const { uploadToS3, computeSHA256, getPresignedUrlFromKey } = require('../lib/s3Upload')
const prisma = require('../lib/client')

const BRAND = {
  primary: '#3C3489',
  accent: '#534AB7',
  light: '#F4F3FE',
  dark: '#26215C',
  green: '#166534',
  amber: '#92400E',
  red: '#991B1B',
  grey: '#6B7280',
  white: '#FFFFFF',
}

class ReportEngine {

  createDoc(options = {}) {
    return new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true,
      info: {
        Title: options.title || 'Sealayer Report',
        Author: 'Sealayer.io',
        Creator: 'Sealayer Report Engine',
      },
      ...options,
    })
  }

  addCoverPage(doc, { reportType, projectName, orgName, dateRange, generatedDate, donorOrgName }) {
    // Top branding area
    doc.rect(0, 0, doc.page.width, 200).fill(BRAND.primary)
    doc.fontSize(12).fillColor(BRAND.light).text('SEALAYER', 50, 40, { align: 'left' })
    doc.fontSize(9).fillColor('#FFFFFFAA').text('Blockchain-verified transparency', 50, 56)

    // Report type heading
    doc.fontSize(28).fillColor(BRAND.white).text(reportType || 'Report', 50, 90, { width: doc.page.width - 100, align: 'left' })

    // Project + org info
    doc.fontSize(12).fillColor(BRAND.light)
    if (projectName) doc.text(projectName, 50, 140)
    if (orgName) doc.text(orgName, 50, 158)

    // Details below banner
    doc.fillColor(BRAND.dark)
    let y = 240
    if (dateRange) {
      doc.fontSize(10).text(`Period: ${dateRange}`, 50, y)
      y += 20
    }
    if (donorOrgName) {
      doc.text(`Donor: ${donorOrgName}`, 50, y)
      y += 20
    }
    doc.text(`Generated: ${generatedDate || new Date().toLocaleDateString('en-GB')}`, 50, y)
    y += 40

    doc.fontSize(9).fillColor(BRAND.grey).text('This report is blockchain-sealed and independently verifiable at verify.sealayer.io', 50, y, { width: doc.page.width - 100 })
  }

  addSectionHeader(doc, title, subtitle) {
    if (doc.y > doc.page.height - 150) doc.addPage()
    doc.moveDown(0.5)
    doc.fontSize(16).fillColor(BRAND.primary).text(title)
    if (subtitle) doc.fontSize(9).fillColor(BRAND.grey).text(subtitle)
    doc.moveDown(0.5)
    // Underline
    const lineY = doc.y
    doc.moveTo(50, lineY).lineTo(doc.page.width - 50, lineY).strokeColor(BRAND.accent).lineWidth(1).stroke()
    doc.moveDown(0.5)
    doc.fillColor(BRAND.dark).fontSize(10)
  }

  addTable(doc, headers, rows, options = {}) {
    const colWidths = options.colWidths || headers.map(() => (doc.page.width - 100) / headers.length)
    const startX = 50

    // Check if we need a new page
    if (doc.y > doc.page.height - 100) doc.addPage()

    // Header row
    let x = startX
    const headerY = doc.y
    doc.rect(startX, headerY, colWidths.reduce((a, b) => a + b, 0), 20).fill(BRAND.primary)
    doc.fontSize(8).fillColor(BRAND.white)
    headers.forEach((h, i) => {
      doc.text(h, x + 4, headerY + 5, { width: colWidths[i] - 8, align: 'left' })
      x += colWidths[i]
    })
    doc.y = headerY + 22

    // Data rows
    doc.fillColor(BRAND.dark).fontSize(8)
    rows.forEach((row, ri) => {
      if (doc.y > doc.page.height - 60) {
        doc.addPage()
        doc.y = 50
      }
      const rowY = doc.y
      if (ri % 2 === 0) {
        doc.rect(startX, rowY, colWidths.reduce((a, b) => a + b, 0), 18).fill('#F9FAFB')
        doc.fillColor(BRAND.dark)
      }
      x = startX
      row.forEach((cell, ci) => {
        doc.text(String(cell ?? '—'), x + 4, rowY + 4, { width: colWidths[ci] - 8, align: 'left' })
        x += colWidths[ci]
      })
      doc.y = rowY + 18
    })
    doc.moveDown(0.5)
  }

  addFooters(doc, hash) {
    const pages = doc.bufferedPageRange()
    for (let i = pages.start; i < pages.start + pages.count; i++) {
      doc.switchToPage(i)
      // Footer line
      const footerY = doc.page.height - 40
      doc.moveTo(50, footerY).lineTo(doc.page.width - 50, footerY).strokeColor('#E5E7EB').lineWidth(0.5).stroke()
      doc.fontSize(7).fillColor(BRAND.grey)
      doc.text('Generated by Sealayer.io — Blockchain-verified transparency', 50, footerY + 8, { width: 300 })
      if (hash) doc.text(`SHA-256: ${hash.substring(0, 24)}...`, 50, footerY + 18, { width: 300 })
      doc.text(`Page ${i + 1} of ${pages.count}`, doc.page.width - 120, footerY + 8, { width: 70, align: 'right' })
      doc.text(new Date().toLocaleDateString('en-GB'), doc.page.width - 120, footerY + 18, { width: 70, align: 'right' })
    }
  }

  addProgressBar(doc, label, value, max, x, y, width) {
    const pct = max > 0 ? Math.min(value / max, 1) : 0
    doc.fontSize(9).fillColor(BRAND.dark).text(`${label}: ${Math.round(pct * 100)}%`, x, y)
    const barY = y + 14
    doc.rect(x, barY, width, 8).fill('#E5E7EB')
    const color = pct >= 0.9 ? BRAND.green : pct >= 0.5 ? BRAND.amber : BRAND.red
    doc.rect(x, barY, width * pct, 8).fill(color)
    return barY + 16
  }

  addKeyValue(doc, key, value, x, y) {
    doc.fontSize(9).fillColor(BRAND.grey).text(key, x, y)
    doc.fontSize(10).fillColor(BRAND.dark).text(String(value ?? '—'), x + 150, y)
    return y + 16
  }

  async generateBuffer(doc) {
    return new Promise((resolve, reject) => {
      const chunks = []
      doc.on('data', c => chunks.push(c))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)
      doc.end()
    })
  }

  async uploadAndSave(buffer, reportId, tenantId, reportData) {
    const hash = computeSHA256(buffer)
    const fileKey = `reports/${tenantId}/${reportId}.pdf`

    const { fileUrl } = await uploadToS3(buffer, `${reportId}.pdf`, tenantId, 'reports')

    // Update GeneratedReport record
    await prisma.$executeRawUnsafe(`
      UPDATE "GeneratedReport" SET
        "fileKey" = $1, "fileUrl" = $2, "fileSizeBytes" = $3,
        hash = $4, status = 'READY', "updatedAt" = NOW()
      WHERE id = $5
    `, fileKey, fileUrl, buffer.length, hash, reportId)

    return { hash, fileKey, fileUrl, size: buffer.length }
  }

  async getPresignedUrl(fileKey) {
    return getPresignedUrlFromKey(fileKey, 3600, { contentType: 'application/pdf' })
  }

  formatCurrency(amount, currency = 'USD') {
    return `${currency} ${Number(amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  }

  formatDate(d) {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  }
}

module.exports = new ReportEngine()
