-- Add OCR extracted values and mismatch flags to Expense
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "ocrAmount" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "ocrVendor" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "ocrDate" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "amountMismatch" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "vendorMismatch" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "dateMismatch" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "mismatchNote" TEXT;
