export interface Currency {
  code: string
  symbol: string
  name: string
  keywords: string[] // extra search terms
}

export const CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$', name: 'US Dollar', keywords: ['united states', 'america'] },
  { code: 'EUR', symbol: '\u20AC', name: 'Euro', keywords: ['european', 'europe'] },
  { code: 'GBP', symbol: '\u00A3', name: 'British Pound', keywords: ['sterling', 'united kingdom', 'uk'] },
  { code: 'AED', symbol: '', name: 'UAE Dirham', keywords: ['emirates', 'dubai', 'abu dhabi'] },
  { code: 'AFN', symbol: '\u060B', name: 'Afghan Afghani', keywords: ['afghanistan'] },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', keywords: ['albania'] },
  { code: 'AMD', symbol: '\u058F', name: 'Armenian Dram', keywords: ['armenia'] },
  { code: 'ANG', symbol: '\u0192', name: 'Netherlands Antillean Guilder', keywords: ['curacao', 'sint maarten'] },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', keywords: ['angola'] },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso', keywords: ['argentina'] },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', keywords: ['australia'] },
  { code: 'AWG', symbol: '\u0192', name: 'Aruban Florin', keywords: ['aruba'] },
  { code: 'AZN', symbol: '\u20BC', name: 'Azerbaijani Manat', keywords: ['azerbaijan'] },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', keywords: ['bosnia'] },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', keywords: ['barbados'] },
  { code: 'BDT', symbol: '\u09F3', name: 'Bangladeshi Taka', keywords: ['bangladesh'] },
  { code: 'BGN', symbol: '\u043B\u0432', name: 'Bulgarian Lev', keywords: ['bulgaria'] },
  { code: 'BHD', symbol: '', name: 'Bahraini Dinar', keywords: ['bahrain'] },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', keywords: ['burundi'] },
  { code: 'BMD', symbol: '$', name: 'Bermudian Dollar', keywords: ['bermuda'] },
  { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', keywords: ['brunei'] },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', keywords: ['bolivia'] },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', keywords: ['brazil'] },
  { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', keywords: ['bahamas'] },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', keywords: ['bhutan'] },
  { code: 'BWP', symbol: 'P', name: 'Botswanan Pula', keywords: ['botswana'] },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', keywords: ['belarus'] },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', keywords: ['belize'] },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', keywords: ['canada'] },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', keywords: ['congo', 'drc', 'democratic republic'] },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', keywords: ['switzerland', 'swiss'] },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', keywords: ['chile'] },
  { code: 'CNY', symbol: '\u00A5', name: 'Chinese Yuan', keywords: ['china', 'renminbi', 'rmb'] },
  { code: 'COP', symbol: '$', name: 'Colombian Peso', keywords: ['colombia'] },
  { code: 'CRC', symbol: '\u20A1', name: 'Costa Rican Col\u00F3n', keywords: ['costa rica'] },
  { code: 'CUP', symbol: '$', name: 'Cuban Peso', keywords: ['cuba'] },
  { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', keywords: ['cabo verde', 'cape verde'] },
  { code: 'CZK', symbol: 'K\u010D', name: 'Czech Koruna', keywords: ['czech', 'czechia'] },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', keywords: ['djibouti'] },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', keywords: ['denmark'] },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', keywords: ['dominican republic'] },
  { code: 'DZD', symbol: '\u062F.\u062C', name: 'Algerian Dinar', keywords: ['algeria'] },
  { code: 'EGP', symbol: 'E\u00A3', name: 'Egyptian Pound', keywords: ['egypt'] },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', keywords: ['eritrea'] },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', keywords: ['ethiopia'] },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', keywords: ['fiji'] },
  { code: 'GEL', symbol: '\u20BE', name: 'Georgian Lari', keywords: ['georgia'] },
  { code: 'GHS', symbol: 'GH\u20B5', name: 'Ghanaian Cedi', keywords: ['ghana'] },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', keywords: ['gambia'] },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', keywords: ['guinea'] },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', keywords: ['guatemala'] },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', keywords: ['guyana'] },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', keywords: ['hong kong'] },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', keywords: ['honduras'] },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', keywords: ['haiti'] },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', keywords: ['hungary'] },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', keywords: ['indonesia'] },
  { code: 'ILS', symbol: '\u20AA', name: 'Israeli New Shekel', keywords: ['israel'] },
  { code: 'INR', symbol: '\u20B9', name: 'Indian Rupee', keywords: ['india'] },
  { code: 'IQD', symbol: '\u0639.\u062F', name: 'Iraqi Dinar', keywords: ['iraq'] },
  { code: 'IRR', symbol: '\uFDFC', name: 'Iranian Rial', keywords: ['iran'] },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Kr\u00F3na', keywords: ['iceland'] },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', keywords: ['jamaica'] },
  { code: 'JOD', symbol: '', name: 'Jordanian Dinar', keywords: ['jordan'] },
  { code: 'JPY', symbol: '\u00A5', name: 'Japanese Yen', keywords: ['japan'] },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', keywords: ['kenya'] },
  { code: 'KGS', symbol: '\u043B\u0432', name: 'Kyrgystani Som', keywords: ['kyrgyzstan'] },
  { code: 'KHR', symbol: '\u17DB', name: 'Cambodian Riel', keywords: ['cambodia'] },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', keywords: ['comoros'] },
  { code: 'KRW', symbol: '\u20A9', name: 'South Korean Won', keywords: ['south korea', 'korea'] },
  { code: 'KWD', symbol: '\u062F.\u0643', name: 'Kuwaiti Dinar', keywords: ['kuwait'] },
  { code: 'KZT', symbol: '\u20B8', name: 'Kazakhstani Tenge', keywords: ['kazakhstan'] },
  { code: 'LAK', symbol: '\u20AD', name: 'Lao Kip', keywords: ['laos'] },
  { code: 'LBP', symbol: 'L\u00A3', name: 'Lebanese Pound', keywords: ['lebanon'] },
  { code: 'LKR', symbol: '\u20A8', name: 'Sri Lankan Rupee', keywords: ['sri lanka'] },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', keywords: ['liberia'] },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', keywords: ['lesotho'] },
  { code: 'LYD', symbol: '\u0644.\u062F', name: 'Libyan Dinar', keywords: ['libya'] },
  { code: 'MAD', symbol: '\u062F.\u0645.', name: 'Moroccan Dirham', keywords: ['morocco'] },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', keywords: ['moldova'] },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', keywords: ['madagascar'] },
  { code: 'MKD', symbol: '\u0434\u0435\u043D', name: 'Macedonian Denar', keywords: ['north macedonia', 'macedonia'] },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', keywords: ['myanmar', 'burma'] },
  { code: 'MNT', symbol: '\u20AE', name: 'Mongolian Tugrik', keywords: ['mongolia'] },
  { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', keywords: ['macau', 'macao'] },
  { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', keywords: ['mauritania'] },
  { code: 'MUR', symbol: '\u20A8', name: 'Mauritian Rupee', keywords: ['mauritius'] },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', keywords: ['maldives'] },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', keywords: ['malawi'] },
  { code: 'MXN', symbol: 'Mex$', name: 'Mexican Peso', keywords: ['mexico'] },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', keywords: ['malaysia'] },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', keywords: ['mozambique'] },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', keywords: ['namibia'] },
  { code: 'NGN', symbol: '\u20A6', name: 'Nigerian Naira', keywords: ['nigeria'] },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan C\u00F3rdoba', keywords: ['nicaragua'] },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', keywords: ['norway'] },
  { code: 'NPR', symbol: '\u20A8', name: 'Nepalese Rupee', keywords: ['nepal'] },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', keywords: ['new zealand'] },
  { code: 'OMR', symbol: '\u0631.\u0639.', name: 'Omani Rial', keywords: ['oman'] },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', keywords: ['panama'] },
  { code: 'PEN', symbol: 'S/.', name: 'Peruvian Sol', keywords: ['peru'] },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', keywords: ['papua new guinea'] },
  { code: 'PHP', symbol: '\u20B1', name: 'Philippine Peso', keywords: ['philippines'] },
  { code: 'PKR', symbol: '\u20A8', name: 'Pakistani Rupee', keywords: ['pakistan'] },
  { code: 'PLN', symbol: 'z\u0142', name: 'Polish Zloty', keywords: ['poland'] },
  { code: 'PYG', symbol: '\u20B2', name: 'Paraguayan Guarani', keywords: ['paraguay'] },
  { code: 'QAR', symbol: '\u0631.\u0642', name: 'Qatari Riyal', keywords: ['qatar'] },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', keywords: ['romania'] },
  { code: 'RSD', symbol: '\u0434\u0438\u043D.', name: 'Serbian Dinar', keywords: ['serbia'] },
  { code: 'RUB', symbol: '\u20BD', name: 'Russian Ruble', keywords: ['russia'] },
  { code: 'RWF', symbol: 'RF', name: 'Rwandan Franc', keywords: ['rwanda'] },
  { code: 'SAR', symbol: '\u0631.\u0633', name: 'Saudi Riyal', keywords: ['saudi arabia'] },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', keywords: ['solomon islands'] },
  { code: 'SCR', symbol: '\u20A8', name: 'Seychellois Rupee', keywords: ['seychelles'] },
  { code: 'SDG', symbol: '\u062C.\u0633.', name: 'Sudanese Pound', keywords: ['sudan'] },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', keywords: ['sweden'] },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', keywords: ['singapore'] },
  { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', keywords: ['sierra leone'] },
  { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', keywords: ['somalia'] },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', keywords: ['suriname'] },
  { code: 'SSP', symbol: '\u00A3', name: 'South Sudanese Pound', keywords: ['south sudan'] },
  { code: 'STN', symbol: 'Db', name: 'S\u00E3o Tom\u00E9 and Pr\u00EDncipe Dobra', keywords: ['sao tome'] },
  { code: 'SYP', symbol: '\u00A3S', name: 'Syrian Pound', keywords: ['syria'] },
  { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', keywords: ['eswatini', 'swaziland'] },
  { code: 'THB', symbol: '\u0E3F', name: 'Thai Baht', keywords: ['thailand'] },
  { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', keywords: ['tajikistan'] },
  { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', keywords: ['turkmenistan'] },
  { code: 'TND', symbol: '\u062F.\u062A', name: 'Tunisian Dinar', keywords: ['tunisia'] },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Pa\u02BBanga', keywords: ['tonga'] },
  { code: 'TRY', symbol: '\u20BA', name: 'Turkish Lira', keywords: ['turkey', 'turkiye'] },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', keywords: ['trinidad', 'tobago'] },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', keywords: ['taiwan'] },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', keywords: ['tanzania'] },
  { code: 'UAH', symbol: '\u20B4', name: 'Ukrainian Hryvnia', keywords: ['ukraine'] },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', keywords: ['uganda'] },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', keywords: ['uruguay'] },
  { code: 'UZS', symbol: 'so\u02BBm', name: 'Uzbekistani Som', keywords: ['uzbekistan'] },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bol\u00EDvar', keywords: ['venezuela'] },
  { code: 'VND', symbol: '\u20AB', name: 'Vietnamese Dong', keywords: ['vietnam'] },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', keywords: ['vanuatu'] },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', keywords: ['samoa'] },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', keywords: ['cameroon', 'chad', 'gabon', 'central african'] },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', keywords: ['east caribbean'] },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', keywords: ['senegal', 'mali', 'burkina faso', 'niger', 'west african'] },
  { code: 'YER', symbol: '\uFDFC', name: 'Yemeni Rial', keywords: ['yemen'] },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', keywords: ['south africa'] },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', keywords: ['zambia'] },
  { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar', keywords: ['zimbabwe'] },
]

/** Format currency for display in selected state: "$ USD" or "KES" */
export function formatCurrencyShort(code: string): string {
  const c = CURRENCIES.find(c => c.code === code)
  if (!c) return code
  return c.symbol ? `${c.symbol} ${c.code}` : c.code
}

/** Format currency for dropdown option: "$ USD — US Dollar" or "KES — Kenyan Shilling" */
export function formatCurrencyOption(c: Currency): string {
  return c.symbol ? `${c.symbol} ${c.code} — ${c.name}` : `${c.code} — ${c.name}`
}

/** Search currencies by code, name, symbol, or keywords */
export function searchCurrencies(query: string): Currency[] {
  if (!query.trim()) return CURRENCIES
  const q = query.toLowerCase()
  return CURRENCIES.filter(c =>
    c.code.toLowerCase().includes(q) ||
    c.name.toLowerCase().includes(q) ||
    c.symbol.toLowerCase().includes(q) ||
    c.keywords.some(k => k.includes(q))
  )
}
